AllCops:
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true